apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:11.0.0-ce.0
        ports:
          - name: ssh
            containerPort: 22
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
          - name: data
            mountPath: /var/opt/gitlab
          - name: config
            mountPath: /etc/gitlab
        #env:
        #  - name: GITLAB_OMNIBUS_CONFIG
        #    value: |
        #      external_url 'http://192.168.99.100:8080';
      volumes:
      - name: data
        hostPath:
          path: /data/gitlab/data
      - name: config
        hostPath:
          path: /data/gitlab/config

---
kind: Service
apiVersion: v1
metadata:
  name: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-ssh
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
