apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
      - name: runner
        image: gitlab/gitlab-runner:v11.0.0
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: config
          mountPath: /etc/gitlab-runner
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: config
        hostPath:
          path: /data/gitlab-runner/config