stages:
  - build
  - package
  - deploy

compile:
  stage: build
  image: golang:1.10.3
  script:
    - go build -ldflags "-linkmode external -extldflags -static" -o example-app
  artifacts:
    paths:
      - example-app
    expire_in: 1 week

dockerbuild:
  stage: package
  image: docker:18.05.0-ce
  script:
    - docker build -t app:${CI_COMMIT_TAG} .
    - docker tag app:${CI_COMMIT_TAG} app:latest

    # Disabled as long as we're running on minikube
    # Since it's all just one VM, any built image will be available immediately, anyway
    #- docker push app:${CI_COMMIT_TAG}
    #- docker push app:latest
  
  only:
    - tags

deploy:
  stage: deploy
  image: quay.io/martinhelmich/k8s-deployer:v1.0.0
  script:
    - helm upgrade --install --set image.get=${CI_COMMIT_TAG} ${CI_PROJECT_NAME} ./chart
  only:
    - tags
